# Generated by Django 2.2.2 on 2019-07-04 04:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20190629_1714'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problem',
            name='num_comments',
        ),
        migrations.RemoveField(
            model_name='problem',
            name='num_likes',
        ),
        migrations.AddField(
            model_name='comment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
